config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'

  resources :sprints do
    resources :task_status
  end

  resources :teams do
    resources :task_status
  end

  resources :tasks
  resources :users
  resources :statuses

  get 'teams/index'
  root 'teams#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_statuses
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task_form.html.erb
<%= form_with model: @task, local: true do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit submitLabel, class: "btn btn-primary" %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'task_form', locals: {submitLabel: "Update Task"} %>
  </div>
</div>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Task Listing</h1>

<%= link_to 'New Task', new_task_path %>

<p></p>

<table class="listing">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td>
        <%= link_to 'Edit', edit_task_path(task) %> |
        <%= link_to 'Destroy', task_path(task),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', teams_path %>

app/views/tasks/new.html.erb
<h1>Create new task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'task_form', locals: {submitLabel: "Create New Task"} %>
  </div>
</div>

<%= link_to 'Back', tasks_path %>