config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'

  resources :sprints do
    resources :task_status
  end

  resources :teams do
    resources :task_status
  end

  resources :tasks
  resources :users
  resources :statuses

  get 'teams/index'
  root 'teams#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  has_many :task_statuses

  validates :name, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 7  }

  before_save :set_end_date
  before_update :set_end_date

  private

  def set_end_date
    self.end = start + duration - 1
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  def index
    @sprints = Sprint.all
  end

  def new
    @sprint = Sprint.new
  end

  def create
    @sprint = Sprint.new(sprint_params)

    if @sprint.save
      redirect_to sprints_path
    else
      render 'new'
    end
  end

  def edit
    @sprint = Sprint.find(params[:id])
  end

  def update
    @sprint = Sprint.find(params[:id])

    if @sprint.update(sprint_params)
      redirect_to sprints_path
    else
      render 'edit'
    end
  end

  def destroy
    @sprint = Sprint.find(params[:id])
    @sprint.destroy

    redirect_to sprints_path
  end

  private

  def sprint_params
    params.require(:sprint).permit(:name, :start, :duration)
  end
end

app/helpers/sprints_helper.rb
module SprintsHelper
  def datepicker_input form, field, startValue
    form.text_field(field, data: { provide: "datepicker",
                                   'date-format': 'yyyy-mm-dd',
                                   'date-autoclose': 'true',
                                   'date-today-btn': 'linked',
                                   'date-today-highlight': 'true',
                                   'value': startValue}).html_safe
  end
end

app/views/sprints/_error_message.html.erb
<% if @sprint.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@sprint.errors.count, "error") %> prohibited
      this sprint from being saved:
    </h2>
    <ul>
      <% @sprint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/sprints/_sprint_form.html.erb
<%= form_with model: @sprint, local: true do |form| %>
  <%= render 'error_message' %>

    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :start %><br>
    <% if @sprint.start.present? %>
      <%= datepicker_input form, :start, @sprint.start %>
    <% else %>
      <%= datepicker_input form, :start, Time.now.strftime('%Y-%m-%d') %>
    <% end %>

    <%= form.label :duration %> (days)
    <%= form.text_field :duration %>

    <%= form.submit submitLabel, class: "btn btn-primary" %>

<% end %>

app/views/sprints/edit.html.erb
<h1>Edit Time Period</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'sprint_form', locals: {submitLabel: "Update Period"} %>
  </div>
</div>

<%= link_to 'Back', sprints_path %>

app/views/sprints/index.html.erb
<h1>Time Period Listing</h1>

<p>
  Today is <%= Time.now.strftime("%m/%d/%Y") %>
</p>

<%= link_to 'New sprint', new_sprint_path %>

<p></p>

<table class="listing">
  <tr>
    <th>Name</th>
    <th>Start</th>
    <th>Ducation</th>
    <th>End</th>
    <th></th>
  </tr>

  <% @sprints.each do |sprint| %>
    <tr>
      <td><%= sprint.name %></td>
      <td><%= sprint.start %></td>
      <td><%= sprint.duration %> days</td>
      <td><%= sprint.end %></td>
      <td>
        <%= link_to 'Edit', edit_sprint_path(sprint) %> |
        <%= link_to 'Destroy', sprint_path(sprint),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', teams_path %>

app/views/sprints/new.html.erb
<h1>Create Time Period</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render partial: 'sprint_form', locals: {submitLabel: "Create New Period"} %>
  </div>
</div>

<%= link_to 'Back', sprints_path %>